spring.jpa:
  hibernate.ddl-auto: create
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

spring.datasource:
  url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
  username: ${RDS_USERNAME}
  password: ${RDS_PASSWORD}